### ISSUE TITLE
CLI: Encryption key & Initialization vector.

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#11]
The CLI parameters `-iv` and `-k` seems useless.
There are default values shown by `-h` but they will be different at execution time.

```
  -iv string
    	Defines initialization vector (default "abDzjL5NVwuEQSyNg5/smg==")
  -k string
    	Defines encryption key (default "JUUJR7QyHZtGX2H/62c+/A==")
```

**Comment by 777777miSSU7777777** [comment]
It seems to me that I need to remove these flags.

**Comment by amaskalenka** [comment]
Replace existing implementation by looking for a token file `.token` in the current directory or in `$HOME` directory.
Rid of encryption. Don't store token in cookies.

**Comment by 777777miSSU7777777** [comment]
Estimated: **4h**
