### ISSUE TITLE
UI: does not display effective scopes

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#17]
Steps to reproduce:

- generate GitHub token
- authenticate in UI with the token
- observe effective scopes
- modify scopes for GitHub token
- go back to UI
- observe scopes (they are not effective)

An user has to reload page or logout/login to observe effective scopes.

**Comment by 777777miSSU7777777** [comment]
I think I need to write script on js to update scopes, but I need plain token instead encrypted.

**Comment by 777777miSSU7777777** [comment]
Estimated: **2h**
