### ISSUE TITLE
Story: Organizations

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#19]
**Description**
As a user I want to see all GitHub organisations I have access to, so that I could enable or disable any them for filtering purposes. I want my choice to be remembered between sessions so that I don’t need to enable/disable organisations every and each time. 

**Acceptance criteria:**
- [ ] _Verify user’s organizations are shown in dropdown-menu_ 
- [ ] _Verify they could be enabled/disabled_ 
- [ ] _Verify user’s choice is remembered between sessions_

**Comment by 777777miSSU7777777** [comment]
**Story**
- create organisation entity and factory for it **2h**
- create query function for list of organisations for provided token **2h**
- create aggregation function for list of organisations **4h**
- create template for dropdown-menu with user organisations **2h**
- user's choice between session with jwt **12h**
  - jwt provier **6h**
  - store user's choice in jwt **6h**
