### ISSUE TITLE
Story: Scopes for Organizations

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#20]
**Description**
As a user I want see “Organizations” dropdown menu disabled if the provided token does not have appropriate permissions. I want to see a popover in “Scopes” pop-up window that indicates why “Organizations” dropdown menu is disabled and what permissions must be granted to the token to make it active. 

**Acceptance criteria**
- [ ] _Verify “Organizations” dropdown menu disabled if a token does not have permissions_ 
- [ ] _Verify “Scopes” pop-up reflects permissions and provides information for “Organizations”_

**Comment by 777777miSSU7777777** [comment]
**Story** 
- On load token check **2h**
- If necessary permissions are presented, dropdown-menu will be enabled with all orgs **4h**
- If necessary permissions aren't presented, drop-menu will be disabled with popover with explanation **4h**
