### ISSUE TITLE
Story: Pull Requests - Opened, by Organization

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#21]
**Description**
As a user I want to see all Pull Requests assigned to me for all enabled Organizations in a separate tab. 

**Acceptance criteria:**
- [ ] Verify all PRs assigned to are displayed in a separate tab 
- [ ] Verify PRs are filtered by selected organizations 
- [ ] Verify a PR item has a link that points to GitHub Pull Request

**Comment by 777777miSSU7777777** [comment]
**Story**
- Repo entity and factory for it **2h**
- Query function for repositories for each enabled organisation **4h**
- Aggregation function for repositories **4h**
- PR entity and factory for it **2h**
- Query function for PRs for each repository **4h**
- Aggregation function for PRs **4h**
- Template for PRs **4h**
