### ISSUE TITLE
Story: Scopes - Pull Requests 

### ISSUE THREAD

**Issue by amaskalenka** [777777miSSU7777777/github-aggregator#22]
**Description**
As a user I want to see a popover in “Scopes” pop-up window that indicates why “Pull Requests” tab is inactive and what permissions must be granted to the token to make it active.

**Acceptance criteria:** 

- [ ] _Verify “Pull Requests” tab disabled if a token does not have permissions_ 
- [ ] _Verify “Scopes” pop-up reflects permissions and provides information for “Pull Requests”_

**Comment by 777777miSSU7777777** [comment]
**Story**
- If necessary permissions are presented, tab with PRs will be enabled **4h**
- If necessary permissions aren't presented, tab with PRs will be disabled and will appear indication with popover with explanation **4h**
